### PR TITLE
New design for index.html

### PR DESCRIPTION
**Pull request by Kudostoy0u**
See how it looks @ https://braindead.kudos.repl.co/

### CODE REVIEW

**Comment by generationzcode** [comment]
this looks great, I'll merge it. I first need to check if it looks pretty to others as well.

**Comment by PoseidonCoder** [comment]
Looks good to me. The font is a little weird though.

**Comment by Kudostoy0u** [comment]
> Looks good to me. The font is a little weird though.

Whole thing is open source, you can modify the font to your heart's content, share the result, and the Replit community can get to decide which font is better on the site.

**Comment by generationzcode** [comment]
this is going to be in version 2, so i might need more help with some more pages, I'll give you guys the designs later

**Comment by 000044Deakin** [comment]
hi do you have something like a company name

**Comment by generationzcode** [comment]
> hi do you have something like a company name

not - we have eggcoin. that is it. maybe replcoin? eggcoin. It is eggcoin

**Comment by generationzcode** [comment]
this is incostistant with other pages. perhaps you can give that pinkish feel to the whole index page, then ima merge

**Comment by Kudostoy0u** [comment]
https://braindead.kudos.repl.co/ see new theme

**Comment by generationzcode** [comment]
amaze

**Pull request merged**
